services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: restaurant
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_TCP_PORT: 3306  # Cấu hình cổng TCP
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Sửa đường dẫn đúng
    networks:
      - my-network
